[ubuntu]
10.0.2.150 ansible_user=ubuntu
10.0.2.140 ansible_user=ubuntu
10.0.2.63 ansible_user=ubuntu

[amazon]
10.0.2.185 ansible_user=ec2-user
10.0.2.136 ansible_user=ec2-user
10.0.2.82 ansible_user=ec2-user

[all:children]
ubuntu
amazon